apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo_un: a3ZrYWx5YW4zNw==
  mongo_pw: cGFzc3cwcmQ=
  #To encode --> echo -n <variablename> | base64
  #To decode --> echo <variablename> | base64 --decode
